import {
  ClientSideRowModelModule,
  ColumnApiModule,
  CsvExportModule,
  ModuleRegistry,
  NumberFilterModule,
  PaginationModule,
  QuickFilterModule,
  RowApiModule,
  RowSelectionModule,
  TextFilterModule,
  themeQuartz,
} from "ag-grid-community";
ModuleRegistry.registerModules([
  ClientSideRowModelModule,
  ColumnApiModule,
  CsvExportModule,
  NumberFilterModule,
  PaginationModule,
  QuickFilterModule,
  RowApiModule,
  RowSelectionModule,
  TextFilterModule,
]);

export const gridTheme = themeQuartz.withParams({
  accentColor: "#059669",
  backgroundColor: "#ffffff",
  foregroundColor: "#1e293b",
  borderColor: "#e2e8f0",
  headerBackgroundColor: "#f8fafc",
  headerTextColor: "#475569",
  fontFamily: "Inter, sans-serif",
  fontSize: 10,
  headerFontSize: 10,
  rowBorder: { color: "#f1f5f9" },
  wrapperBorder: false,
  cellHorizontalPadding: 18,
  selectedRowBackgroundColor: "#ecfdf5",
  checkboxBorderRadius: 4,
});
